//This is where you'll need to swap out the names
//and info for your PAX, I advise setting up a
//spreadsheet in GoogleDocs, so it can be referred
//to fo quicker reference.

var exhibitors = [
  { "boothNumber":"3342",
    "exhibitorName":"Comcast",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3344",
    "exhibitorName":"Corsair",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3346",
    "exhibitorName":"Machinima",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3444",
    "exhibitorName":"Klei",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3630",
    "exhibitorName":"Square Enix",
    "sectionNumber":"2",
    "zoneNumber":"1",
    "exhibitorAssistant":"Virus",
    "assistantContact":"203-383-3023",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3646",
    "exhibitorName":"S2 Games",
    "sectionNumber":"2",
    "zoneNumber":"1",
    "exhibitorAssistant":"Virus",
    "assistantContact":"203-383-3023",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3330",
    "exhibitorName":"Xaviant",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3625",
    "exhibitorName":"Sony Online Entertainment",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },


]
