//This is where you'll need to swap out the names
//and info for your PAX, I advise setting up a
//spreadsheet in GoogleDocs, so it can be referred
//to fo quicker reference.
$(document).ready(function() {

var exhibitors = [
  { "boothNumber":"3342",
    "exhibitorName":"Comcast",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"216-926-4997",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"internet, Comcast" },

  { "boothNumber":"3344",
    "exhibitorName":"Corsair",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"216-926-4997",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3346",
    "exhibitorName":"Machinima",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"216-926-4997",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3444",
    "exhibitorName":"Klei",
    "sectionNumber":"1",
    "zoneNumber":"1",
    "exhibitorAssistant":"Van",
    "assistantContact":"216-926-4997",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3630",
    "exhibitorName":"Square Enix",
    "sectionNumber":"2",
    "zoneNumber":"1",
    "exhibitorAssistant":"Virus",
    "assistantContact":"203-383-3023",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3646",
    "exhibitorName":"S2 Games",
    "sectionNumber":"2",
    "zoneNumber":"1",
    "exhibitorAssistant":"Virus",
    "assistantContact":"203-383-3023",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3330",
    "exhibitorName":"Xaviant",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"425-773-9874",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3625",
    "exhibitorName":"Sony Online Entertainment",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"425-773-9874",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"sony, " },

  { "boothNumber":"3834",
    "exhibitorName":"Gunnar Optiks",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"425-773-9874",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3828(Satellite)",
    "exhibitorName":"Logitech",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"425-773-9874",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3822",
    "exhibitorName":"Sanshee",
    "sectionNumber":"3",
    "zoneNumber":"1",
    "exhibitorAssistant":"Checkmate",
    "assistantContact":"425-773-9874",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3603, 3617",
    "exhibitorName":"Wargaming.net",
    "sectionNumber":"4",
    "zoneNumber":"1",
    "exhibitorAssistant":"WingedVictory",
    "assistantContact":"440-840-5487",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3808",
    "exhibitorName":"UDON",
    "sectionNumber":"4",
    "zoneNumber":"1",
    "exhibitorAssistant":"WingedVictory",
    "assistantContact":"440-840-5487",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3810",
    "exhibitorName":"Flying Frog",
    "sectionNumber":"4",
    "zoneNumber":"1",
    "exhibitorAssistant":"WingedVictory",
    "assistantContact":"440-840-5487",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3812",
    "exhibitorName":"Plyngo",
    "sectionNumber":"4",
    "zoneNumber":"1",
    "exhibitorAssistant":"WingedVictory",
    "assistantContact":"440-840-5487",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3403",
    "exhibitorName":"Twitch TV",
    "sectionNumber":"5",
    "zoneNumber":"1",
    "exhibitorAssistant":"Evanthesquirrel",
    "assistantContact":"508-360-7335",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3417",
    "exhibitorName":"Pokemon",
    "sectionNumber":"5",
    "zoneNumber":"1",
    "exhibitorAssistant":"Evanthesquirrel",
    "assistantContact":"508-360-7335",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3411",
    "exhibitorName":"Kixeye",
    "sectionNumber":"5",
    "zoneNumber":"1",
    "exhibitorAssistant":"Evanthesquirrel",
    "assistantContact":"508-360-7335",
    "zoneLeader":"WingedVictory",
    "leaderContact":"440-840-5487",
    "exhibitorKeywords":"" },

  { "boothNumber":"3117",
    "exhibitorName":"Skull Candy",
    "sectionNumber":"6",
    "zoneNumber":"2",
    "exhibitorAssistant":"Azazel",
    "assistantContact":"530-318-1768",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3217",
    "exhibitorName":"Capcom",
    "sectionNumber":"6",
    "zoneNumber":"2",
    "exhibitorAssistant":"Azazel",
    "assistantContact":"530-318-1768",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3010, 3020",
    "exhibitorName":"SuperGiant Games",
    "sectionNumber":"7",
    "zoneNumber":"2",
    "exhibitorAssistant":"Dannicus",
    "assistantContact":"952-393-3314",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3002",
    "exhibitorName":"Spyparty",
    "sectionNumber":"7",
    "zoneNumber":"2",
    "exhibitorAssistant":"Dannicus",
    "assistantContact":"952-393-3314",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3003, 3004",
    "exhibitorName":"The Behemoth",
    "sectionNumber":"7",
    "zoneNumber":"2",
    "exhibitorAssistant":"Dannicus",
    "assistantContact":"952-393-3314",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3103",
    "exhibitorName":"Intel",
    "sectionNumber":"8",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mori-Neko",
    "assistantContact":"310-713-3225",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3209",
    "exhibitorName":"Uber Entertainment",
    "sectionNumber":"8",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mori-Neko",
    "assistantContact":"310-713-3225",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"3203",
    "exhibitorName":"Gaems",
    "sectionNumber":"8",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mori-Neko",
    "assistantContact":"310-713-3225",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 9",
    "exhibitorName":"ThinkGeek",
    "sectionNumber":"8",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mori-Neko",
    "assistantContact":"310-713-3225",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 7",
    "exhibitorName":"Chessex",
    "sectionNumber":"8",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mori-Neko",
    "assistantContact":"310-713-3225",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 1",
    "exhibitorName":"Mayfair Games",
    "sectionNumber":"9",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mr Sandman",
    "assistantContact":"425-770-5635",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 2",
    "exhibitorName":"White Lotus Wishes",
    "sectionNumber":"9",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mr Sandman",
    "assistantContact":"425-770-5635",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 5",
    "exhibitorName":"Privateer Press",
    "sectionNumber":"9",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mr Sandman",
    "assistantContact":"425-770-5635",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 10",
    "exhibitorName":"Dark Horse",
    "sectionNumber":"9",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mr Sandman",
    "assistantContact":"425-770-5635",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"Sky 3",
    "exhibitorName":"Geek Chic HQ",
    "sectionNumber":"9",
    "zoneNumber":"2",
    "exhibitorAssistant":"Mr Sandman",
    "assistantContact":"425-770-5635",
    "zoneLeader":"Dannicus",
    "leaderContact":"952-393-3314",
    "exhibitorKeywords":"" },

  { "boothNumber":"2046, 2030, 2014",
    "exhibitorName":"Bethesda",
    "sectionNumber":"10",
    "zoneNumber":"3",
    "exhibitorAssistant":"LordOwen",
    "assistantContact":"336-688-8019",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1642",
    "exhibitorName":"Wizards of the Coast",
    "sectionNumber":"10",
    "zoneNumber":"3",
    "exhibitorAssistant":"LordOwen",
    "assistantContact":"336-688-8019",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"814, 1414",
    "exhibitorName":"2K Games",
    "sectionNumber":"11",
    "zoneNumber":"3",
    "exhibitorAssistant":"Kurpav",
    "assistantContact":"425-443-8775",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1814",
    "exhibitorName":"Logitech",
    "sectionNumber":"11",
    "zoneNumber":"3",
    "exhibitorAssistant":"Kurpav",
    "assistantContact":"425-443-8775",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1230",
    "exhibitorName":"6 ft",
    "sectionNumber":"12",
    "zoneNumber":"3",
    "exhibitorAssistant":"Valkyrion",
    "assistantContact":"401-787-4982",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"six, feet, foot" },

  { "boothNumber":"1430",
    "exhibitorName":"MSI",
    "sectionNumber":"12",
    "zoneNumber":"3",
    "exhibitorAssistant":"Valkyrion",
    "assistantContact":"401-787-4982",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1640",
    "exhibitorName":"WB Games",
    "sectionNumber":"12",
    "zoneNumber":"3",
    "exhibitorAssistant":"Valkyrion",
    "assistantContact":"401-787-4982",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1246",
    "exhibitorName":"Alienware",
    "sectionNumber":"13",
    "zoneNumber":"3",
    "exhibitorAssistant":"Loki",
    "assistantContact":"248-535-7778",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1240",
    "exhibitorName":"EVGA",
    "sectionNumber":"13",
    "zoneNumber":"3",
    "exhibitorAssistant":"Loki",
    "assistantContact":"248-535-7778",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },

  { "boothNumber":"1438",
    "exhibitorName":"Sandisk",
    "sectionNumber":"13",
    "zoneNumber":"3",
    "exhibitorAssistant":"Loki",
    "assistantContact":"248-535-7778",
    "zoneLeader":"Loki",
    "leaderContact":"248-535-7778",
    "exhibitorKeywords":"" },


]
$(".matches").match(function() {
    var showMatches = exhibitors.match(xaname:exhibitorAssistant)
    });
});
